<?php

/**
 * @file
 * Contains recreate_block_from_config.module.
 */

use Drush\Drush;
use Consolidation\SiteAlias\SiteAliasManager;
/**
 * Implements hook_help().
 */
function recreate_block_from_config_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the recreate_block_content module.
    case 'help.page.recreate_block_from_config':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This will recreate block(s) from config on drush cr or install.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_rebuild().
 */
function recreate_block_from_config_rebuild() {
  // partially import any config that is in /config/install whenever drush cr is called.
  // There might be a more efficient way of doing this, but it works.
  $self_record = new SiteAliasManager();
  $options = ['yes' => true, 'partial' => true, 'source' => 'modules/custom/recreate_block_from_config/config/install' ];
  $args = [];
  $process = Drush::drush($self_record->getSelf(), 'config-import', $args, $options);
  $process->run($process->showRealtime()->hideStdout());
}

