name: recreate_block_from_config
type: module
description: This will recreate block(s) from config on drush cr or install
core: 8.x
core_version_requirement: ^8 || ^9
#dependencies:
#  - drupal:block_content


